apiVersion: apps/v1
kind: Deployment

metadata:
  name: game-theory-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: game-theory-backend

  template:
    metadata:
      labels:
        app: game-theory-backend

    spec:
      containers:
      - name: backend
        image: 851218292096.dkr.ecr.ap-south-1.amazonaws.com/game-theory-backend:9
        imagePullPolicy: Always

        ports:
        - containerPort: 5000
