apiVersion: v1
kind: Service
metadata:
  name: game-theory-service
  namespace: game-theory

spec:
  selector:
    app: game-theory-backend

  type: NodePort

  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
